//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GreyMatterSocialNet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OptionVote
    {
        public int Id { get; set; }
        public int VoterId { get; set; }
        public int OptionId { get; set; }
    }
}
