//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GreyMatterSocialNet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Outcome
    {
        public int Id { get; set; }
        public int OptionId { get; set; }
        public int SituationId { get; set; }
        public string Name { get; set; }
        public string DisplayText { get; set; }
        public int CreatorId { get; set; }
        public string PictureAddress { get; set; }
        public System.DateTime CreatedOnUtc { get; set; }
        public System.DateTime UpdatedOnUtc { get; set; }
        public int UpVotes { get; set; }
        public int DownVotes { get; set; }
    }
}
